
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "./_Components/Footer/Footer";
import Navbar from "./_Components/Navbar/Navbar";



import '@fortawesome/fontawesome-free/css/all.min.css'
import { Toaster } from "_/components/ui/sonner";

import MySessionProvider from "./_Components/MySessionProvider/MySessionProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Frsh Cart E-Commerce App ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >

     




          <MySessionProvider>





            
            <div className="px-10">
              
              <Navbar />
              {children} 
              <Toaster />
            </div>
           

            <Footer />

          </MySessionProvider>





      </body>
    </html>
  );
}
